name: 'Packages: Controls.UserDialogs.Maui'

on:
    push:
        branches:
            - main
        paths:
            - '**'
    pull_request:
        branches:
            - main
        paths:
            - '**'

concurrency:
    group: packages-cs-${{ github.ref }}
    cancel-in-progress: ${{ github.event_name == 'pull_request' }}

env:
    DOTNET_CLI_TELEMETRY_OPTOUT: true
    BUILD_PUSH: true
    DO_NOT_TRACK: '1'
    NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
    contents: write
    packages: write

jobs:
  publish:
    runs-on: ubuntu-latest
    # runs-on: windows-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.0.x
            9.0.x

      - name: Extract Version
        run: |
          $version = (Select-Xml -Path '.\Controls.UserDialogs.Maui\Controls.UserDialogs.Maui.csproj' -XPath '//Version').Node.InnerText.Trim()
          "NUGET_VERSION=$version" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Build Library
        run: dotnet build .\Controls.UserDialogs.Maui\Controls.UserDialogs.Maui.csproj -c Release

      - name: Build Nuget
        run: dotnet pack .\Controls.UserDialogs.Maui\Controls.UserDialogs.Maui.csproj -c Release -o pack

      - name: Upload Nuget
        run: |
          dotnet nuget push .\pack\Controls.UserDialogs.Maui.*.nupkg --source github_cenozon
